### ISSUE TITLE
Create a tag for version releases

### ISSUE THREAD

**Issue by marimeireles** [rmorshea/spectate#35]
Hi @rmorshea I'm using your package in a jupyter widget I'm creating and I need to support it on [conda forge](https://conda-forge.org). 
For that I need to create a feedstock in the conda repository and it's recommended to add a tag to support versioning. The tag should have the same version number as the Pypi package.

It's not really mandatory and I'll make the package anyway, but according to the maintainers it's recommended. 

Let me know if I can help with that and if you're interested in being added as a maintainer of the conda feedstock package.

Thanks for the great work! =)

**Comment by rmorshea** [comment]
@marimeireles sorry I didn't see this. I'd be happy to add you as a maintainer.

**Comment by marimeireles** [comment]
Actually, I meant if you wanted to be included in the feedstock as a maintainer https://github.com/conda-forge/spectate-feedstock, so you can have merging privileges on conda forge when a new release of Spectate is out.
I just added you as a contributor =)
And thanks :)
