### ISSUE TITLE
CI for spectate

### ISSUE THREAD

**Issue by marimeireles** [rmorshea/spectate#47]
Hey Ryan, would you be interested in having a CI for spectate?

Also, I'm interested in knowing if spectate runs in Windows.

**Comment by rmorshea** [comment]
Given that `spectate` is pure Python I'd expect it to run fine on windows. I don't have a Windows machine myself though so I don't really have the ability to easily check that.

As for CI, I've got a basic test suite that runs in Travis, but anything extra would be great. Do you want to run an integration test against `ipycytoscape` specifically?

**Comment by marimeireles** [comment]
Yeah.
Sorry, I was under the impression ipycytoscape didn't run on windows because of spectate, but I was wrong. Thanks Ryan. :)
