### ISSUE TITLE
Maintaining after merger into ipywidgets or traitlets.

### ISSUE THREAD

**Issue by draperjames** [rmorshea/spectate#5]
Hi @rmorshea,

 I'm very impressed with you work. I've been wanting something like `EventfulDict` for building my custom ipywidgets for a while now and this exceeds all expectations. I've read in the of the old traitlets and ipwidgets issues and PRs that there are plans to incorporate these types. All that would be great but it appears like that may take while before it is implemented. So I was planning on using this in the interim and I'd like to know if you plan to keep this repo open and up to date with whatever flavor of merger that ends up going down? If so I'd like to volunteer to help maintain it. 

Best, 

James

**Comment by rmorshea** [comment]
@draperjames, I'm heading into a widgets workshop next week, and hope to get eventful traits merged with a dependency on `spectate`. Even if that doesn't happen, I intend to keep this around and updated.
